import EXTERNAL_MISMATCH from "./EXTERNAL_MISMATCH.ts";
import INTERNAL_MISMATCH from "./INTERNAL_MISMATCH.ts";
import INVALID_DEV_AND_PEER_DEPENDENCY_RELATIONSHIP from "./INVALID_DEV_AND_PEER_DEPENDENCY_RELATIONSHIP.ts";
import INVALID_PACKAGE_NAME from "./INVALID_PACKAGE_NAME.ts";
import MULTIPLE_DEPENDENCY_TYPES from "./MULTIPLE_DEPENDENCY_TYPES.ts";
import ROOT_HAS_PROD_DEPENDENCIES from "./ROOT_HAS_PROD_DEPENDENCIES.ts";
import UNSORTED_DEPENDENCIES from "./UNSORTED_DEPENDENCIES.ts";
import INCORRECT_REPOSITORY_FIELD from "./INCORRECT_REPOSITORY_FIELD.ts";
import WORKSPACE_REQUIRED from "./WORKSPACE_REQUIRED.ts";

export let checks = {
  EXTERNAL_MISMATCH,
  INTERNAL_MISMATCH,
  INVALID_DEV_AND_PEER_DEPENDENCY_RELATIONSHIP,
  INVALID_PACKAGE_NAME,
  MULTIPLE_DEPENDENCY_TYPES,
  ROOT_HAS_PROD_DEPENDENCIES,
  UNSORTED_DEPENDENCIES,
  INCORRECT_REPOSITORY_FIELD,
  WORKSPACE_REQUIRED,
};
