name: Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The npm tag to publish to"
        required: true
        type: choice
        options:
          - latest
          - test
  push:
    branches:
      - main
    paths:
      - "**/CHANGELOG.md"

concurrency: publish

permissions: {} # each job should define its own permission explicitly

jobs:
  publish:
    name: Publish
    if: github.repository == 'Thinkmill/manypkg'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: Release
    permissions:
      contents: write # to push tags
      id-token: write # to use OpenID Connect token for trusted publishing (changesets/action)
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/ci-setup
        with:
          node-version: 24

      - run: yarn build

      - name: git config
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: version packages
        if: inputs.tag == 'test'
        run: |
          yarn changeset version --snapshot ${{ inputs.tag }}
          git commit -a -m 'test'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: npm publish, git tag
        run: yarn changeset publish --tag ${{ inputs.tag || 'latest' }}

      # reset, then we have a tagged dangling commit
      - name: git push
        if: inputs.tag == 'test'
        run: |
          git reset HEAD~1 --hard

      - run: git push origin --tags
